spring:
 application:
  name:Lajoac

datasource:
  url: jdbc:postgresql://localhost:5432/lajoac
  username: lajoac
  password: lajoac
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  redis:
    host: localhost
    port: 6379

flyway:
  enabled: true
  locations: classpath:db/migration